entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: me@showmewhatyougot.live
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: www
