apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jitsi-my-bogon-shop
  namespace: cert-manager
spec:
  isCA: false
  commonName: jitsi-my-bogon-shop
  secretName: letsencrypt-prod
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-my-bogon-shop
  namespace: cert-manager
spec:
  isCA: false
  commonName: gitea-my-bogon-shop
  secretName: letsencrypt-prod
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
