apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kong-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: kong-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: kong
