replicas: 1

rbac:
  enabled: true

accessLogs:
  enabled: true

dashboard:
  enabled: true
  domain: lb.bogon.shop
  auth:
    basic:
     # admin: password
      admin: '$apr1$xd1kpMTs$qFcsWe0VjLuTSJB3MihOV0' ☠️☠️☠️

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:754977136847:certificate/687722c1-72a6-449b-ac51-8c44b5f90fd8"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

externalTrafficPolicy: Local

ssl:
  enabled: true
  enforced: true
  upstream: true
 
