              

- name: HashiCorp - Setup Terraform

  uses: hashicorp/setup-terraform@v2.0.3
steps:
- uses: hashicorp/setup-terraform@v2
  with:
    cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

- name: Terraform fmt
  id: fmt
  run: terraform fmt -check
  continue-on-error: true 
